### ISSUE TITLE
Compilar a web de modo automático

### ISSUE THREAD

**Issue by tomasalmeida** [vigojug/vigojug.github.io#9]
Compilamos a mano o lanzamos via travis?

**Comment by antonmry** [comment]
Polo de agora, mellor a mano #10 Mirarei o de travis en canto teña un minuto (tamén a opción de meter o gradle)..

**Comment by tomasalmeida** [comment]
Perfecto, yo estoy un poco liado esta semana, pero voy a ver si hay algún plug in para minificar html (si sabes de alguno, bienvenido será)

**Comment by antonmry** [comment]
Se non é urxente, espera un pouco, e xa o metemos co gradle todo xunto, ok?

Este ten boa pinta e xa o estamos a usar: https://github.com/eriwen/gradle-js-plugin

**Comment by antonmry** [comment]
Estiven botando un ollo a isto, e non sei si merece a pena. O fixen fai tempo e podo recuperalo pero é bastante chollo...

Propoño que o que aprove o cambio, despois faga un:

```
git checkout source
git pull
./gradlew clean bake publishGhPages
```

e con iso queda feito. 

@tomasalmeida ¿qué che parece?

**Comment by tomasalmeida** [comment]
```
[composite-build] Configuring build: /Users/tomas/Personal/VigoJUG/github/jbake-gradle-plugin
:jbake-gradle-plugin:compileJava NO-SOURCE
:jbake-gradle-plugin:compileGroovy UP-TO-DATE
:jbake-gradle-plugin:pluginDescriptors UP-TO-DATE
:jbake-gradle-plugin:processResources UP-TO-DATE
:jbake-gradle-plugin:classes UP-TO-DATE
:jbake-gradle-plugin:jar
:jbake-gradle-plugin:javadocJar UP-TO-DATE
:jbake-gradle-plugin:sourcesJar UP-TO-DATE
:clean
:bake
Current implementation of storage does not support sbtree collections
Current implementation of storage does not support sbtree collections
:prepareGhPages FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':prepareGhPages'.
> Problem cloning repository.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':prepareGhPages'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
```

@antonmry te suena este error?

**Comment by antonmry** [comment]
No lo había probado porque la PR todavía no estaba aprobada, pero acabo de hacerlo y funcionó a la primera.

Si ha fallado, pueden ser dos cosas:

- No tengas la rama master descargada o actualizada (no creo).
- El remote lo tienes por HTTPS en lugar de por SSH.

@tomasalmeida ¿puede ser la segunda?

**Comment by tomasalmeida** [comment]
es la segunda. Uso https casi siempre.Si te funciona ok, para mi caso ya descargaré por ssh.

**Comment by antonmry** [comment]
Ok, yo no uso https, no se lleva muy bien con la MFA :-(
